### ISSUE TITLE
Question about active_mode auto-enabling in ESPHome

### ISSUE THREAD

**Issue by xangin** [hberntsen/mhi-ac-ctrl-esp32#17]
Dear @hberntsen ,

First of all, thank you for developing this integration! It has been working great overall. However, I encountered an issue where the `active_mode` switch automatically turns off when the module is powered on.

I noticed that it can be enabled using a blueprint, but I would prefer to have it automatically enabled within ESPHome itself, so I don’t have to rely on a blueprint.

I have tried using `restore_mode`, but it seems that this parameter is not supported. I also attempted to turn on the switch during boot, but I received the following error:

    "ID 'myswitch1' of type MhiAcCtrl doesn't inherit from switch_::Switch. Please double-check your ID is pointing to the correct value."

Is there any other way to achieve this? I would really appreciate your guidance.

Thank you in advance for your help!

**Comment by hberntsen** [comment]
Note that the activation via Home Assistant has advantages:
1. ESPHome has a 15 minute auto reboot when there is no connection. On reboot the active mode is off so the AC will also turn off by itself. That prevents that the AC runs when you can't control it any more.
2. While the network/Home Assistant is down you can use timers with the remote again while you are fixing things :).

Though, if you still want to activate it on the device, this works for me:

```yaml 
esphome:
  on_boot:
    then:
      - switch.turn_on: ${device_id}_active_mode

switch:
  - platform: MhiAcCtrl
    mhi_ac_ctrl_id: ${mhi_device_id}
    active_mode:
      name: ${device_name} Active mode
      id: ${device_id}_active_mode
```

I've also added support for `restore_mode` for it, so this should work as well now:

```yaml
switch:
  - platform: MhiAcCtrl
    mhi_ac_ctrl_id: ${mhi_device_id}
    active_mode:
      name: ${device_name} Active mode
      id: ${device_id}_active_mode
      restore_mode: ALWAYS_ON
```

**Comment by xangin** [comment]
Hi @hberntsen ,

Thank you for your detailed explanation and for adding support for `restore_mode`! 

I really appreciate you taking the time to modify the code specifically for my request. Your support means a lot!

I have implemented the changes based on your suggestions, and they work perfectly for my needs. Everything is now functioning exactly as I had hoped.

Once again, thank you so much for your help and for your amazing work on this project! 😊

**Comment by hberntsen** [comment]
Thank you for your response! It is really nice to hear my work was valuable to you!

**Comment by xangin** [comment]
Hi @hberntsen ,

I have a quick question regarding the `status_led` behavior.

Does your code include handling for `status_led`?
If the module has already been added to Home Assistant but the air conditioner hasn't been physically connected yet, will the `status_led` keep blinking until the AC is properly connected?

Just wanted to confirm how this part behaves. Thank you again! 😊

**Comment by harm-nedap** [comment]
Hi @xangin 

For #10 I added some handling: https://github.com/search?q=repo%3Ahberntsen%2Fmhi-ac-ctrl-esp32-c3%20status_&type=code . I'm not using the status led myself (not visible because my module is inside the AC), so this is untested. It should blink when the AC is not connected!

**Comment by hberntsen** [comment]
Hi @xangin 

For #10 I added some handling: https://github.com/search?q=repo%3Ahberntsen%2Fmhi-ac-ctrl-esp32-c3%20status_&type=code . I'm not using the status led myself (not visible because my module is inside the AC), so this is untested. It should blink when the AC is not connected!

**Comment by xangin** [comment]
Hi @hberntsen ,

Thank you for the clarification and for pointing me to the code reference!

Good to know that the `status_led` is intended to blink when the AC is not connected — that’s exactly the behavior I was curious about. Even if it’s untested, it’s helpful to understand how it should work.

I really appreciate your continued support. Thanks again!

**Comment by CV8R** [comment]
Apologies that I am late to the party!

My solution to switching the active_mode enabled only when ESP is connected to Home Assistant was to use the following in the YAML config.

```
api:
  encryption:
    key: "A-Key-Goes-Here"
  on_client_connected:
    - wait_until:
        condition:
          api.connected:
            state_subscription_only: true
    - switch.turn_on: ${device_id}_active_mode
  on_client_disconnected:
    - if:
        condition:
          not:
            api.connected:
              state_subscription_only: true
        then:
          - switch.turn_off: ${device_id}_active_mode
```

To assist with an automation I also added, but don't use it now, but nice to have.

```
binary_sensor:
  - platform: status
    name: "Device Status"
```

And while not relevant to this issue topic added these guys. Restart is handy to have when testing.

```
button:
  - platform: restart
    name: "Restart"
    entity_category: diagnostic
 
  - platform: safe_mode
    id: button_safe_mode
    name: "Safe Mode Boot"
    entity_category: diagnostic
 
  - platform: factory_reset
    id: factory_reset_btn
    name: "Factory Reset"
    entity_category: diagnostic
```

**Comment by hberntsen** [comment]
Never too late! It's nice to see people come up with different solutions! Do note that in this setup, when your Home Assistant is offline for 5 minutes, your AC will already decide to turn itself off. That can upset people in your household when doing upgrades and stuff ;).

With ESPHome fixing more and more WiFi issues, I can imagine them dropping the default automatic-restart-when-there-is-no-API-connection-for-15-minutes thing in the future (the `api: reboot_timeout:`). in order to not rely on that restart, we could use a timer. I was thinking of making this the standard way to enable and disable active mode:

```yaml
api:
  encryption:
    key: "your key here"
  on_client_connected:
    - wait_until:
        condition:
          api.connected:
            state_subscription_only: true
    - switch.turn_on: ${device_id}_active_mode
    - script.stop: turn_off_delayed

  on_client_disconnected:
    - script.execute: turn_off_delayed

script:
  - id: turn_off_delayed
    mode: single
    then:
      - delay: 5min
      - if:
          condition:
            not:
              api.connected:
                state_subscription_only: true
          then:
            - switch.turn_off: ${device_id}_active_mode
```

The delay timer adds 5 minutes on top of the AC's built in 5 minutes. Feedback?
